version: "3"

services:
  react:
    container_name: frontend
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        - REACT_APP_API_HOST=${REACT_APP_API_HOST}
        - REACT_APP_DOMAIN_LIST=${REACT_APP_DOMAIN_LIST}
    ports:
      - 3080:80
